### ISSUE TITLE
能否请教一下如何转换为CCITT a-Law，8000Hz, 8bits, Mono格式的WAV文件

### ISSUE THREAD

**Issue by wy08** [codemonkeybulucck/opencore-amrDemo-iOS#1]
完全看不懂C语言，求助

**Comment by codemonkeybulucck** [comment]
你是说amr转换为wav文件吗？

**Comment by wy08** [comment]
是的，我用了你的demo去转换，可是每次得到的都不符合这个需求，
发自网易邮箱大师
在2017年05月27日 13:38，codemonkeybulucck 写道： 你是说amr转换为wav文件吗？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codemonkeybulucck/opencore-amrDemo-iOS","title":"codemonkeybulucck/opencore-amrDemo-iOS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codemonkeybulucck/opencore-amrDemo-iOS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@codemonkeybulucck in #1: 你是说amr转换为wav文件吗？"}],"action":{"name":"View Issue","url":"https://github.com/codemonkeybulucck/opencore-amrDemo-iOS/issues/1#issuecomment-304429553"}}}

**Comment by codemonkeybulucck** [comment]
应该是不符合的，这个demo只是做了8k和16k的pcm和amr的互转，但我看到你那里有个ccitt alaw的东西，这个我之前没见过，我晚上帮你看看，如果你找到什么资料也可以发给我看看。

**Comment by wy08** [comment]
好的，十分感谢。alaw主要用于通信之间，三大运营商用的比较多，我之前试了FFMPEG转码的方式，可是也不行，后来，我直接录音的时候设置formatID为alaw，得到录取的音频用音频软件查看是符合的，但是上传给我司后台也可以，但是对接联通公司的服务端却出现格式不正确。
发自网易邮箱大师
在2017年05月27日 14:04，codemonkeybulucck 写道： 应该是不符合的，这个demo只是做了8k和16k的pcm和amr的互转，但我看到你那里有个ccitt alaw的东西，这个我之前没见过，我晚上帮你看看，如果你找到什么资料也可以发给我看看。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codemonkeybulucck/opencore-amrDemo-iOS","title":"codemonkeybulucck/opencore-amrDemo-iOS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codemonkeybulucck/opencore-amrDemo-iOS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@codemonkeybulucck in #1: 应该是不符合的，这个demo只是做了8k和16k的pcm和amr的互转，但我看到你那里有个ccitt alaw的东西，这个我之前没见过，我晚上帮你看看，如果你找到什么资料也可以发给我看看。"}],"action":{"name":"View Issue","url":"https://github.com/codemonkeybulucck/opencore-amrDemo-iOS/issues/1#issuecomment-304430699"}}}

**Comment by wy08** [comment]
能否加你的QQ进行交流？我的QQ1123231279/675325168
发自网易邮箱大师
在2017年05月27日 14:10，wy08 写道： 
好的，十分感谢。alaw主要用于通信之间，三大运营商用的比较多，我之前试了FFMPEG转码的方式，可是也不行，后来，我直接录音的时候设置formatID为alaw，得到录取的音频用音频软件查看是符合的，但是上传给我司后台也可以，但是对接联通公司的服务端却出现格式不正确。
发自网易邮箱大师
在2017年05月27日 14:04，codemonkeybulucck 写道： 应该是不符合的，这个demo只是做了8k和16k的pcm和amr的互转，但我看到你那里有个ccitt alaw的东西，这个我之前没见过，我晚上帮你看看，如果你找到什么资料也可以发给我看看。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codemonkeybulucck/opencore-amrDemo-iOS","title":"codemonkeybulucck/opencore-amrDemo-iOS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codemonkeybulucck/opencore-amrDemo-iOS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@codemonkeybulucck in #1: 应该是不符合的，这个demo只是做了8k和16k的pcm和amr的互转，但我看到你那里有个ccitt alaw的东西，这个我之前没见过，我晚上帮你看看，如果你找到什么资料也可以发给我看看。"}],"action":{"name":"View Issue","url":"https://github.com/codemonkeybulucck/opencore-amrDemo-iOS/issues/1#issuecomment-304430699"}}}

**Comment by codemonkeybulucck** [comment]
好的，我已经加你qq了。

**Comment by wy08** [comment]
我试了那个方式，直接修改参数确实无法转换格式，
发自网易邮箱大师
在2017年05月27日 19:48，codemonkeybulucck 写道： 好的，我已经加你qq了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/codemonkeybulucck/opencore-amrDemo-iOS","title":"codemonkeybulucck/opencore-amrDemo-iOS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/codemonkeybulucck/opencore-amrDemo-iOS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@codemonkeybulucck in #1: 好的，我已经加你qq了。"}],"action":{"name":"View Issue","url":"https://github.com/codemonkeybulucck/opencore-amrDemo-iOS/issues/1#issuecomment-304447128"}}}
