### ISSUE TITLE
16k采样率问题咨询

### ISSUE THREAD

**Issue by zhangxiweicaochen** [codemonkeybulucck/opencore-amrDemo-iOS#2]
我刚才试了一下您的16k采样率转amr，我看了一下生成的amr不能播放，能帮忙给看一下咋回事吗？联系方式：QQ 736815161 多谢帮助。

**Comment by codemonkeybulucck** [comment]
我刚刚试了一下，demo里面生成amr是可以播放的。或者你试着换一个播放器试试看看能不能播放

**Comment by zhangxiweicaochen** [comment]
之前忘了回复了。8k采样率转amr播放没有任何问题，16k的转完我换了好几种播放器都不能播放，最后我只能把16k的重采样成8k，然后进行转amr解决了此问题。
