### ISSUE TITLE
opencore库转化耗时太长

### ISSUE THREAD

**Issue by linwenbang** [codemonkeybulucck/opencore-amrDemo-iOS#3]
使用的时候，发现转码效率比上另外的库时间慢上大概5倍左右，后面发现，替换新版本编译后的lib库即可，大概是因为这个demo时间太久，lib库也太久了，我就留个言，感谢大大的贡献

**Comment by codemonkeybulucck** [comment]
感谢你的issues，我已经很久没有关注过这个库了，我更新一下。
